name: Android CI
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew test

      - name: Release Build
        run: ./gradlew assembleRelease